### ISSUE TITLE
some end values are empty

### ISSUE THREAD

**Issue by cameralibre** [ssbc/visual-docs#3]
Sometimes when using multiple keyframes, the final 'to' value is not recorded.
Example:
```javascript
    tl
      .add({
	changeBegin: function(anim) {
          logAnimations(anim)
          console.log(anim)
         },
	targets: '#symbol-wave-a',
        keyframes: [
          { opacity: [0, 1], duration: 500 },
          { opacity: [1, 1], duration: 500 },
          { opacity: [1, 0], duration: 500 },
          { opacity: [0, 1], duration: 500 }
        ],
        delay: anime.stagger(250)
      })
```
This produces the following CSS:
```css
#symbol-wave-a { animation-name: symbol-wave-a-anim; } 
@keyframes symbol-wave-a-anim {
  0% { opacity:0; }
  25% { opacity:1; }
  50% { opacity:1; }
  75% { opacity:0; }
  100% { }
}
```
