### ISSUE TITLE
transforms are not combined

### ISSUE THREAD

**Issue by cameralibre** [ssbc/visual-docs#4]
### Context:
 
* [How to use the conversion script](https://github.com/ssbc/visual-docs/blob/main/js/README.md)
* [My approach to writing the script](https://github.com/ssbc/visual-docs/blob/main/js/rubber-ducky.md)

### Problem
Currently when there are `transform` properties being animated, they are not correctly formatted or combined into a single transform property. 

Current output: 
```css
@keyframes animation-name {
  0% { scale:0; } /* not valid css! */
  10% { translate-x:0px; scale:1; }  /* translateX should also not be converted to kebab-case */
  100% { translate-x:10px; scale:0; }
}
```
Correct output: 
```css
@keyframes animation-name {
  0% { transform: scale(0); } 
  10% { transform: translateX(0) scale(1); }
  100% { transform: translateX(10px) scale(0); }
}
```
in the anime.js `anim` object there are two entries which should help me here:

- the value of `anim.animations[i].type` can be either `css` or `transform` (maybe more? But I haven't seen anything else)
- anim.animatables[i].transforms stores a `list` array and a `last` value. For the above animation, it looks like this:
`anim.animatables[0].transforms`:
```javascript
{
 "list": {​
   0: scale → 0
​​​​​​   1: translateX → "10px" 
},
 "last": "translateX"
}
```
weirdly, it is exactly the same for `anim.animatables[1].transforms` & `anim.animatables[2].transforms`...?
